# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
darkMode = true
darkToggle = true
logo = "images/logo.png"
description = "VRM Add-on for Blender"
mainSections = ["section1", "section2"]
# robots = ""

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = false

[article]
  showDate = true
  dateFormat = "2 January 2006"
  showAuthor = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  editURL = "https://github.com/saturday06/VRM_Addon_for_Blender/tree/gh-pages"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = false
  showReadingTime = true
  showWordCount = false
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = false
  showSummary = false
  groupByYear = true

[taxonomy]
  showTermCount = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
